/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Greg
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.JList;

public class user_menu extends javax.swing.JFrame {

    /**
     * Creates new form user_menu
     */
    UserAccount currentUser;
    
    public user_menu(UserAccount user, boolean adim) {
        initComponents();
        this.setTitle("Admin Menu");     //Adds a title to the frame
        setLocationRelativeTo(null);    //Centers the frame in the middle of ths screen
        currentUser = user;
        //MenuPanel.setVisible(false);
        adminMenu.setVisible(true);
        ProfilePanel.setVisible(false);
        getBuilds();
    }
    public user_menu(UserAccount user) {
        initComponents();
        this.setTitle("User Menu");     //Adds a title to the frame
        setLocationRelativeTo(null);    //Centers the frame in the middle of ths screen
        currentUser = user;
        getBuilds();
    }
    public user_menu() {
        this.setTitle("User Menu");     //Adds a title to the frame
        setLocationRelativeTo(null);    //Centers the frame in the middle of ths screen
    }

    
    private void viewProfile(){
    MenuPanel.setVisible(false);
        adminMenu.setVisible(false);
        ProfilePanel.setVisible(true);

        fname.setText(currentUser.getFname());
        sname.setText(currentUser.getSname());

        email.setText(currentUser.getEmail());

  
    }
    
    
    
    private void getBuilds(){
        buildsList.removeAll();
    ArrayList builds = new ArrayList();
         builds = currentUser.getBuilds();
    
    System.out.println(builds);
    
    DefaultListModel model = new DefaultListModel();
    //model.clear();
    for (Object str : builds) { 		      
          // System.out.println(str); 	
          model.addElement(str);
          
      }

    buildsList.setModel(model);
  }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        buildsList = new javax.swing.JList<>();
        adminMenu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnEditComp = new javax.swing.JButton();
        btnCreateAcc = new javax.swing.JButton();
        btnDeleteAcc = new javax.swing.JButton();
        btnAddComp = new javax.swing.JButton();
        btnCreateBuild = new javax.swing.JButton();
        btnViewBuild = new javax.swing.JButton();
        btnAddMake = new javax.swing.JButton();
        btnNewComponent = new javax.swing.JButton();
        btnEditBuild = new javax.swing.JButton();
        btnEditAcc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        profileBtn = new javax.swing.JButton();
        logOffBtn = new javax.swing.JButton();
        ProfilePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        goBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        MenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenuPanel.setMaximumSize(new java.awt.Dimension(900, 700));
        MenuPanel.setMinimumSize(new java.awt.Dimension(900, 700));
        MenuPanel.setPreferredSize(new java.awt.Dimension(900, 700));
        MenuPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setText("MENU");
        MenuPanel.add(jLabel1);
        jLabel1.setBounds(370, 160, 128, 60);

        jLabel3.setText("View/Edit builds ");
        MenuPanel.add(jLabel3);
        jLabel3.setBounds(400, 240, 110, 14);

        buildsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        buildsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(buildsList);

        MenuPanel.add(jScrollPane1);
        jScrollPane1.setBounds(240, 260, 410, 140);

        adminMenu.setBackground(new java.awt.Color(255, 255, 204));
        adminMenu.setMaximumSize(new java.awt.Dimension(900, 700));
        adminMenu.setMinimumSize(new java.awt.Dimension(900, 700));
        adminMenu.setPreferredSize(new java.awt.Dimension(900, 700));
        adminMenu.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel7.setText("Admin");
        adminMenu.add(jLabel7);
        jLabel7.setBounds(360, 20, 170, 60);

        btnEditComp.setText("Edit Component");
        btnEditComp.setMaximumSize(new java.awt.Dimension(117, 23));
        btnEditComp.setMinimumSize(new java.awt.Dimension(117, 23));
        btnEditComp.setPreferredSize(new java.awt.Dimension(117, 23));
        btnEditComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCompActionPerformed(evt);
            }
        });
        adminMenu.add(btnEditComp);
        btnEditComp.setBounds(340, 120, 117, 23);

        btnCreateAcc.setText("Create Account");
        btnCreateAcc.setMaximumSize(new java.awt.Dimension(117, 23));
        btnCreateAcc.setMinimumSize(new java.awt.Dimension(117, 23));
        btnCreateAcc.setPreferredSize(new java.awt.Dimension(117, 23));
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });
        adminMenu.add(btnCreateAcc);
        btnCreateAcc.setBounds(200, 90, 120, 23);

        btnDeleteAcc.setText("View Accounts");
        btnDeleteAcc.setMaximumSize(new java.awt.Dimension(117, 23));
        btnDeleteAcc.setMinimumSize(new java.awt.Dimension(117, 23));
        btnDeleteAcc.setPreferredSize(new java.awt.Dimension(117, 23));
        btnDeleteAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccActionPerformed(evt);
            }
        });
        adminMenu.add(btnDeleteAcc);
        btnDeleteAcc.setBounds(340, 90, 117, 23);

        btnAddComp.setText("View Components");
        btnAddComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompActionPerformed(evt);
            }
        });
        adminMenu.add(btnAddComp);
        btnAddComp.setBounds(200, 120, 120, 23);

        btnCreateBuild.setText("Create Build");
        btnCreateBuild.setMaximumSize(new java.awt.Dimension(117, 23));
        btnCreateBuild.setMinimumSize(new java.awt.Dimension(117, 23));
        btnCreateBuild.setPreferredSize(new java.awt.Dimension(117, 23));
        btnCreateBuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBuildActionPerformed(evt);
            }
        });
        adminMenu.add(btnCreateBuild);
        btnCreateBuild.setBounds(200, 150, 120, 23);

        btnViewBuild.setText("View Builds");
        btnViewBuild.setMaximumSize(new java.awt.Dimension(117, 23));
        btnViewBuild.setMinimumSize(new java.awt.Dimension(117, 23));
        btnViewBuild.setPreferredSize(new java.awt.Dimension(117, 23));
        btnViewBuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBuildActionPerformed(evt);
            }
        });
        adminMenu.add(btnViewBuild);
        btnViewBuild.setBounds(480, 90, 120, 23);

        btnAddMake.setText("Add New Make");
        btnAddMake.setMaximumSize(new java.awt.Dimension(117, 23));
        btnAddMake.setMinimumSize(new java.awt.Dimension(117, 23));
        btnAddMake.setPreferredSize(new java.awt.Dimension(117, 23));
        btnAddMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMakeActionPerformed(evt);
            }
        });
        adminMenu.add(btnAddMake);
        btnAddMake.setBounds(480, 150, 117, 23);

        btnNewComponent.setText("New Component");
        btnNewComponent.setMaximumSize(new java.awt.Dimension(117, 23));
        btnNewComponent.setMinimumSize(new java.awt.Dimension(117, 23));
        btnNewComponent.setPreferredSize(new java.awt.Dimension(117, 23));
        btnNewComponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewComponentActionPerformed(evt);
            }
        });
        adminMenu.add(btnNewComponent);
        btnNewComponent.setBounds(480, 120, 117, 23);

        btnEditBuild.setText("Edit Build");
        btnEditBuild.setMaximumSize(new java.awt.Dimension(117, 23));
        btnEditBuild.setMinimumSize(new java.awt.Dimension(117, 23));
        btnEditBuild.setPreferredSize(new java.awt.Dimension(117, 23));
        btnEditBuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBuildActionPerformed(evt);
            }
        });
        adminMenu.add(btnEditBuild);
        btnEditBuild.setBounds(630, 90, 100, 23);

        btnEditAcc.setText("Edit Account");
        btnEditAcc.setMaximumSize(new java.awt.Dimension(117, 23));
        btnEditAcc.setMinimumSize(new java.awt.Dimension(117, 23));
        btnEditAcc.setPreferredSize(new java.awt.Dimension(117, 23));
        btnEditAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccActionPerformed(evt);
            }
        });
        adminMenu.add(btnEditAcc);
        btnEditAcc.setBounds(340, 150, 120, 23);

        MenuPanel.add(adminMenu);
        adminMenu.setBounds(0, 520, 900, 180);
        adminMenu.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        profileBtn.setText("Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        logOffBtn.setText("LogOff");
        logOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOffBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOffBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuPanel.add(jPanel1);
        jPanel1.setBounds(737, 10, 160, 60);

        getContentPane().add(MenuPanel);
        MenuPanel.setBounds(-1, -1, 900, 710);

        ProfilePanel.setBackground(new java.awt.Color(255, 255, 255));
        ProfilePanel.setMaximumSize(new java.awt.Dimension(830, 440));
        ProfilePanel.setMinimumSize(new java.awt.Dimension(830, 440));
        ProfilePanel.setPreferredSize(new java.awt.Dimension(830, 440));
        ProfilePanel.setRequestFocusEnabled(false);
        ProfilePanel.setLayout(null);

        jLabel2.setText("Fname");
        ProfilePanel.add(jLabel2);
        jLabel2.setBounds(70, 110, 70, 14);

        fname.setText("Fname");
        ProfilePanel.add(fname);
        fname.setBounds(160, 110, 140, 14);

        jLabel4.setText("Sname");
        ProfilePanel.add(jLabel4);
        jLabel4.setBounds(70, 140, 70, 14);

        sname.setText("Sname");
        ProfilePanel.add(sname);
        sname.setBounds(160, 140, 160, 14);

        jLabel6.setText("email");
        ProfilePanel.add(jLabel6);
        jLabel6.setBounds(70, 170, 60, 14);

        email.setText("email");
        ProfilePanel.add(email);
        email.setBounds(160, 170, 230, 14);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel5.setText("Profile");
        ProfilePanel.add(jLabel5);
        jLabel5.setBounds(180, 20, 220, 60);

        goBack.setText("Go Back");
        goBack.setToolTipText("");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        ProfilePanel.add(goBack);
        goBack.setBounds(60, 320, 100, 23);

        getContentPane().add(ProfilePanel);
        ProfilePanel.setBounds(30, 54, 840, 440);
        ProfilePanel.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        viewProfile();
        //System.out.println(currentUser.getFname());
        //fname.setText("fuck");
    }//GEN-LAST:event_profileBtnActionPerformed

    private void logOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOffBtnActionPerformed
     
        LogIn frm = new LogIn(); //opens admin user form
        this.setVisible(false);
        frm.setVisible(true);
        
        currentUser.reset();
        
        
    }//GEN-LAST:event_logOffBtnActionPerformed

    private void btnEditCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCompActionPerformed

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        this.setVisible(false);
        new CreateAccountAdmin().setVisible(true);
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnDeleteAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccActionPerformed
        this.setVisible(false);
        //new DeleteAccount().setVisible(true);
    }//GEN-LAST:event_btnDeleteAccActionPerformed

    private void btnAddCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompActionPerformed
        this.setVisible(false);
        //new AddComponent().setVisible(true);
    }//GEN-LAST:event_btnAddCompActionPerformed

    private void btnCreateBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBuildActionPerformed
        this.setVisible(false);
        new CreateBuild().setVisible(true);
    }//GEN-LAST:event_btnCreateBuildActionPerformed

    private void btnViewBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBuildActionPerformed
        this.setVisible(false);
        new CreateBuild().setVisible(true);
    }//GEN-LAST:event_btnViewBuildActionPerformed

    private void btnAddMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMakeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddMake().setVisible(true);
    }//GEN-LAST:event_btnAddMakeActionPerformed

    private void btnNewComponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewComponentActionPerformed
        // TODO add your handling code here:
        String[] choices = {"Accessory", "CPU", "Cooler", "GPU", "Make", "Motherboard", "Case", "PSU", "RAM", "Storage"};
        String input = (String) JOptionPane.showInputDialog(null, "Which type of part is being added?",
            "New Part", JOptionPane.QUESTION_MESSAGE, null, // Use
            // default
            // icon
            choices, // Array of choices
            choices[0]); // Initial choice
        switch (input) {

            case "Accessory":
            break;

            case "CPU":
            this.setVisible(false);
            new AddCPU(currentUser).setVisible(true);
            break;

            case "Motherboard":
            this.setVisible(false);
            new AddMotherboard(currentUser).setVisible(true);
            break;

            case "RAM":
            this.setVisible(false);
            new addRAM(currentUser).setVisible(true);
            break;

        }
    }//GEN-LAST:event_btnNewComponentActionPerformed

    private void btnEditBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBuildActionPerformed
        String[] choices = {"Build 1", "Build 2", "Build 3"};
        //Need build names here to be pulled from DB
        String input = (String) JOptionPane.showInputDialog(null, "Which build would you like to edit?",
            "Edit Build", JOptionPane.QUESTION_MESSAGE, null, // Use
            // default
            // icon
            choices, // Array of choices
            choices[0]); // Initial choice
        switch (input) {

            case "Build 1":
            this.setVisible(false);
            new EditBuild(currentUser, input).setVisible(true);
            break;

            case "Build 2":
            this.setVisible(false);
            new EditBuild(currentUser, input).setVisible(true);
            break;

            case "Build 3":
            this.setVisible(false);
            new EditBuild(currentUser, input).setVisible(true);
            break;
        }
    }//GEN-LAST:event_btnEditBuildActionPerformed

    private void btnEditAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditAccActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        if(currentUser.getType() == true){
         MenuPanel.setVisible(true);
        adminMenu.setVisible(true);
        ProfilePanel.setVisible(false);

        }else{
         MenuPanel.setVisible(true);
        adminMenu.setVisible(false);
        ProfilePanel.setVisible(false);

        }
        
        
        
    }//GEN-LAST:event_goBackActionPerformed

    private void buildsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildsListMouseClicked
        
        
        System.out.println(buildsList.getSelectedValue());
        
        String selectedBuild = buildsList.getSelectedValue();
        String username = currentUser.getUsername();
        
        view_build frm = new view_build(currentUser,selectedBuild); //
        this.dispose();
        frm.setVisible(true);
    }//GEN-LAST:event_buildsListMouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
       
 

        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_menu().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel adminMenu;
    private javax.swing.JButton btnAddComp;
    private javax.swing.JButton btnAddMake;
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnCreateBuild;
    private javax.swing.JButton btnDeleteAcc;
    private javax.swing.JButton btnEditAcc;
    private javax.swing.JButton btnEditBuild;
    private javax.swing.JButton btnEditComp;
    private javax.swing.JButton btnNewComponent;
    private javax.swing.JButton btnViewBuild;
    private javax.swing.JList<String> buildsList;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fname;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOffBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JLabel sname;
    // End of variables declaration//GEN-END:variables
}
